### ISSUE TITLE
Configuring an HTTP external authz service for EnvoyFilter resource

### ISSUE THREAD

**Issue by mefarazath** [istio/proxy#1985]
I am trying to enforce authorization for inbound traffic to the istio proxy. I used the "envoy.ext_authz" EnvoyFilter resource and implemented a GRPC server to do the authorization. Here is my working config

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz-grpc
  namespace: istio-system
spec:          
  workloadLabels:
    app: httpbin
  filters:                          
  - insertPosition:
      index: FIRST
    listenerMatch: 
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    filterType: HTTP
    filterName: "envoy.ext_authz"
    filterConfig:      
      grpc_service:
        google_grpc:          
          target_uri: external-auth-grpc-server:8080
          stat_prefix: "ext_authz"
  - insertPosition:
      index: FIRST
    listenerMatch:                  
      listenerType: SIDECAR_INBOUND
      listenerProtocol: TCP
    filterType: NETWORK
    filterName: "envoy.ext_authz"
    filterConfig:                        
      grpc_service:   
        google_grpc:                    
          target_uri: external-auth-grpc-server:8080
          stat_prefix: "ext_authz"
```

While going through the [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2alpha/ext_authz.proto#envoy-api-msg-config-filter-http-ext-authz-v2alpha-httpservice) I also noticed that there is an option to have an HTTP server to do the authorization which I think would be much convenient to me. I tried different combinations of the config as I couldn't find a proper example

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: http-authz-inbound-authz
  namespace: istio-system
spec:          
  workloadLabels:
    app: httpbin
  filters:                          
  - insertPosition:
      index: FIRST
    listenerMatch: 
      listenerType: SIDECAR_INBOUND
      listenerProtocol: HTTP
    filterType: HTTP
    filterName: "envoy.ext_authz"
    filterConfig:      
      http_service:
          server_uri:
            uri: http://http-authz:8080/http-authz/inbound
            cluster: outbound|8080||http-authz.default.svc.cluster.local
            timeout: 10s
  - insertPosition:
      index: FIRST
    listenerMatch:                  
      listenerType: SIDECAR_INBOUND
      listenerProtocol: TCP
    filterType: NETWORK
    filterName: "envoy.ext_authz"
    filterConfig:                        
      http_service:
          server_uri:
            uri: http://http-authz:8080/http-authz/inbound
            cluster: outbound|8080||http-authz.default.svc.cluster.local
            timeout: 10s
```

Each one resulted in either the envoy crashing and restarting or request not sent to the http service. 
Is having an HTTP service as an external authorization service supported in istio?
Particularly, what would be the correct value for 'cluster' to be used? A sample configuration would be awesome.

```
  http_service:
          server_uri:
            uri: http://http-authz:8080/http-authz/inbound
            cluster: outbound|8080||http-authz.default.svc.cluster.local
            timeout: 10s
```

I found a similar issue related to http external authorization service in https://groups.google.com/forum/#!topic/istio-users/cmC5odtmItY as well.

Thanks in advance for the help!
