### ISSUE TITLE
istio-proxy is only able to passthrough around 62 grpc request per second

### ISSUE THREAD

**Issue by lnshi** [istio/proxy#2000]
As title told, we use [istio-proxy](docker.io/istio/proxy_init:1.0.1) as sidecar for one of our grpc server, then we attack the server at a rate 1000 grpc request per-second, on our grpc server side we only observed around 62 request per-second coming in(our grpc server CPU usage and memory usage is still very low, 10% and 200MiB like that, they are in different container, so will not share any resources, and istio-proxy container has sufficient guaranteed resources: 2cpu and 3Gi memory).

If we disable the istio-proxy sidecar, then attack in the same rate, we can successfully observe the exactly same rate as attacker told, and the cpu and memory is properly/fully consumed.

What could be the issues? Do i need some special configurations to handle high concurrency load? Pls help.

@qiwzhang @lizan @kyessenov

**Comment by qiwzhang** [comment]
What happen to other requests that did not reach backend?   What response were they failed with?

Well,  we did not test grpc.  But we constantly test with http.  We can get much better performance than 62 qps.   As far as I can tell,   grpc is using http2, all Envoy code is based on http2 so http and grpc should have the same data path, should have the same performance.

@mandarjog.   do you have any grpc performance data?

**Comment by qiwzhang** [comment]
In our perf test, we basically have a dummy Mixer without much policy, so Check calls can be cached at proxy side with very high cache hit ratio. 

 In your test,  what kind of Mixer policies do you have?   What is the Check cache hit ratio?

@mandarjog do you know how to chec cache hit ratiio?

I know there is such statics:

total_check_calls
total_remote_check_calls

you can get these numbers of Envoy admin port.

**Comment by lizan** [comment]
@Inshi Can you provide more details about your request pattern? (# of connections, payload size, test client etc).

What is the CPU usage of the istio-proxy container?

**Comment by lnshi** [comment]
After i tried below scenario, i got more confused, basically i took out the istio-proxy sidecar from my grpc server, and run one envoy as front proxy standalone, then attack the envoy proxy directly, i can reach around 466 qps(it should be 1000,  the envoy container resources are not fully utilized, peak CPU 0.704 of 2, memory 37.8Mi of 2Gi):

![screen shot 2018-10-25 at 14 55 43](https://user-images.githubusercontent.com/24580114/47481441-3018de00-d866-11e8-8747-f5a7ed175421.png)

My Dockerfile.envoy
```
FROM envoyproxy/envoy-alpine:latest

COPY envoy/envoy.yaml /etc/envoy/envoy.yaml

CMD /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
```
My envoy.yaml
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 53547 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: service_grpc }
          http_filters:
          - name: envoy.router
  clusters:
  - name: service_grpc
    connect_timeout: 30s
    type: STATIC
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    http2_protocol_options: { }
    hosts: [{ socket_address: { address: 100.64.72.26, port_value: 53547 }}]
```

This is if i attack my grpc server directly:

![screen shot 2018-10-25 at 15 10 54](https://user-images.githubusercontent.com/24580114/47482128-3d36cc80-d868-11e8-8b0e-46c5e802b641.png)

@qiwzhang  How to check the istio-proxy outbound metrics?

@lizan the attacker always has one grpc connection to the target, the request payload is consistent: 170KB, actually it is a TensorFlow Serving predict call.

**Comment by lizan** [comment]
Can you paste you stats here? (i.e. `curl http://127.0.0.1:9901/stats`).

What is the client are you using, and how many concurrent requests does it issue? It is likely some network factor is affecting since CPU is not fully utilized.

**Comment by lnshi** [comment]
@lizan 

```
cluster.service_grpc.bind_errors: 0
cluster.service_grpc.external.upstream_rq_200: 5615
cluster.service_grpc.external.upstream_rq_2xx: 5615
cluster.service_grpc.external.upstream_rq_503: 92103
cluster.service_grpc.external.upstream_rq_504: 5224
cluster.service_grpc.external.upstream_rq_5xx: 97327
cluster.service_grpc.external.upstream_rq_completed: 102942
cluster.service_grpc.http2.header_overflow: 0
cluster.service_grpc.http2.headers_cb_no_stream: 0
cluster.service_grpc.http2.rx_messaging_error: 0
cluster.service_grpc.http2.rx_reset: 0
cluster.service_grpc.http2.too_many_header_frames: 0
cluster.service_grpc.http2.trailers: 0
cluster.service_grpc.http2.tx_reset: 9235
cluster.service_grpc.lb_healthy_panic: 0
cluster.service_grpc.lb_local_cluster_not_ok: 0
cluster.service_grpc.lb_recalculate_zone_structures: 0
cluster.service_grpc.lb_subsets_active: 0
cluster.service_grpc.lb_subsets_created: 0
cluster.service_grpc.lb_subsets_fallback: 0
cluster.service_grpc.lb_subsets_removed: 0
cluster.service_grpc.lb_subsets_selected: 0
cluster.service_grpc.lb_zone_cluster_too_small: 0
cluster.service_grpc.lb_zone_no_capacity_left: 0
cluster.service_grpc.lb_zone_number_differs: 0
cluster.service_grpc.lb_zone_routing_all_directly: 0
cluster.service_grpc.lb_zone_routing_cross_zone: 0
cluster.service_grpc.lb_zone_routing_sampled: 0
cluster.service_grpc.max_host_weight: 0
cluster.service_grpc.membership_change: 1
cluster.service_grpc.membership_healthy: 1
cluster.service_grpc.membership_total: 1
cluster.service_grpc.original_dst_host_invalid: 0
cluster.service_grpc.retry_or_shadow_abandoned: 0
cluster.service_grpc.update_attempt: 0
cluster.service_grpc.update_empty: 0
cluster.service_grpc.update_failure: 0
cluster.service_grpc.update_no_rebuild: 0
cluster.service_grpc.update_success: 0
cluster.service_grpc.upstream_cx_active: 1
cluster.service_grpc.upstream_cx_close_notify: 0
cluster.service_grpc.upstream_cx_connect_attempts_exceeded: 0
cluster.service_grpc.upstream_cx_connect_fail: 0
cluster.service_grpc.upstream_cx_connect_timeout: 0
cluster.service_grpc.upstream_cx_destroy: 0
cluster.service_grpc.upstream_cx_destroy_local: 0
cluster.service_grpc.upstream_cx_destroy_local_with_active_rq: 0
cluster.service_grpc.upstream_cx_destroy_remote: 0
cluster.service_grpc.upstream_cx_destroy_remote_with_active_rq: 0
cluster.service_grpc.upstream_cx_destroy_with_active_rq: 0
cluster.service_grpc.upstream_cx_http1_total: 0
cluster.service_grpc.upstream_cx_http2_total: 1
cluster.service_grpc.upstream_cx_idle_timeout: 0
cluster.service_grpc.upstream_cx_max_requests: 0
cluster.service_grpc.upstream_cx_none_healthy: 0
cluster.service_grpc.upstream_cx_overflow: 0
cluster.service_grpc.upstream_cx_protocol_error: 0
cluster.service_grpc.upstream_cx_rx_bytes_buffered: 242
cluster.service_grpc.upstream_cx_rx_bytes_total: 210964
cluster.service_grpc.upstream_cx_total: 1
cluster.service_grpc.upstream_cx_tx_bytes_buffered: 0
cluster.service_grpc.upstream_cx_tx_bytes_total: 1391147104
cluster.service_grpc.upstream_flow_control_backed_up_total: 2318
cluster.service_grpc.upstream_flow_control_drained_total: 2156
cluster.service_grpc.upstream_flow_control_paused_reading_total: 0
cluster.service_grpc.upstream_flow_control_resumed_reading_total: 0
cluster.service_grpc.upstream_rq_200: 5615
cluster.service_grpc.upstream_rq_2xx: 5615
cluster.service_grpc.upstream_rq_503: 92103
cluster.service_grpc.upstream_rq_504: 5224
cluster.service_grpc.upstream_rq_5xx: 97327
cluster.service_grpc.upstream_rq_active: 1024
cluster.service_grpc.upstream_rq_cancelled: 0
cluster.service_grpc.upstream_rq_completed: 102942
cluster.service_grpc.upstream_rq_maintenance_mode: 0
cluster.service_grpc.upstream_rq_pending_active: 0
cluster.service_grpc.upstream_rq_pending_failure_eject: 0
cluster.service_grpc.upstream_rq_pending_overflow: 92103
cluster.service_grpc.upstream_rq_pending_total: 0
cluster.service_grpc.upstream_rq_per_try_timeout: 0
cluster.service_grpc.upstream_rq_retry: 0
cluster.service_grpc.upstream_rq_retry_overflow: 0
cluster.service_grpc.upstream_rq_retry_success: 0
cluster.service_grpc.upstream_rq_rx_reset: 0
cluster.service_grpc.upstream_rq_timeout: 5224
cluster.service_grpc.upstream_rq_total: 11863
cluster.service_grpc.upstream_rq_tx_reset: 5224
cluster.service_grpc.version: 0
cluster_manager.active_clusters: 1
cluster_manager.cluster_added: 1
cluster_manager.cluster_modified: 0
cluster_manager.cluster_removed: 0
cluster_manager.cluster_updated: 0
cluster_manager.cluster_updated_via_merge: 0
cluster_manager.update_merge_cancelled: 0
cluster_manager.update_out_of_merge_window: 0
cluster_manager.warming_clusters: 0
filesystem.flushed_by_timer: 0
filesystem.reopen_failed: 0
filesystem.write_buffered: 0
filesystem.write_completed: 0
filesystem.write_total_buffered: 0
http.admin.downstream_cx_active: 1
http.admin.downstream_cx_delayed_close_timeout: 0
http.admin.downstream_cx_destroy: 0
http.admin.downstream_cx_destroy_active_rq: 0
http.admin.downstream_cx_destroy_local: 0
http.admin.downstream_cx_destroy_local_active_rq: 0
http.admin.downstream_cx_destroy_remote: 0
http.admin.downstream_cx_destroy_remote_active_rq: 0
http.admin.downstream_cx_drain_close: 0
http.admin.downstream_cx_http1_active: 1
http.admin.downstream_cx_http1_total: 1
http.admin.downstream_cx_http2_active: 0
http.admin.downstream_cx_http2_total: 0
http.admin.downstream_cx_idle_timeout: 0
http.admin.downstream_cx_overload_disable_keepalive: 0
http.admin.downstream_cx_protocol_error: 0
http.admin.downstream_cx_rx_bytes_buffered: 87
http.admin.downstream_cx_rx_bytes_total: 87
http.admin.downstream_cx_ssl_active: 0
http.admin.downstream_cx_ssl_total: 0
http.admin.downstream_cx_total: 1
http.admin.downstream_cx_tx_bytes_buffered: 0
http.admin.downstream_cx_tx_bytes_total: 0
http.admin.downstream_cx_websocket_active: 0
http.admin.downstream_cx_websocket_total: 0
http.admin.downstream_flow_control_paused_reading_total: 0
http.admin.downstream_flow_control_resumed_reading_total: 0
http.admin.downstream_rq_1xx: 0
http.admin.downstream_rq_2xx: 0
http.admin.downstream_rq_3xx: 0
http.admin.downstream_rq_4xx: 0
http.admin.downstream_rq_5xx: 0
http.admin.downstream_rq_active: 1
http.admin.downstream_rq_completed: 0
http.admin.downstream_rq_http1_total: 1
http.admin.downstream_rq_http2_total: 0
http.admin.downstream_rq_idle_timeout: 0
http.admin.downstream_rq_non_relative_path: 0
http.admin.downstream_rq_overload_close: 0
http.admin.downstream_rq_response_before_rq_complete: 0
http.admin.downstream_rq_rx_reset: 0
http.admin.downstream_rq_too_large: 0
http.admin.downstream_rq_total: 1
http.admin.downstream_rq_tx_reset: 0
http.admin.downstream_rq_ws_on_non_ws_route: 0
http.admin.rs_too_large: 0
http.async-client.no_cluster: 0
http.async-client.no_route: 0
http.async-client.rq_direct_response: 0
http.async-client.rq_redirect: 0
http.async-client.rq_total: 0
http.ingress_http.downstream_cx_active: 1
http.ingress_http.downstream_cx_delayed_close_timeout: 0
http.ingress_http.downstream_cx_destroy: 0
http.ingress_http.downstream_cx_destroy_active_rq: 0
http.ingress_http.downstream_cx_destroy_local: 0
http.ingress_http.downstream_cx_destroy_local_active_rq: 0
http.ingress_http.downstream_cx_destroy_remote: 0
http.ingress_http.downstream_cx_destroy_remote_active_rq: 0
http.ingress_http.downstream_cx_drain_close: 0
http.ingress_http.downstream_cx_http1_active: 0
http.ingress_http.downstream_cx_http1_total: 0
http.ingress_http.downstream_cx_http2_active: 1
http.ingress_http.downstream_cx_http2_total: 1
http.ingress_http.downstream_cx_idle_timeout: 0
http.ingress_http.downstream_cx_overload_disable_keepalive: 0
http.ingress_http.downstream_cx_protocol_error: 0
http.ingress_http.downstream_cx_rx_bytes_buffered: 4164
http.ingress_http.downstream_cx_rx_bytes_total: 11744456357
http.ingress_http.downstream_cx_ssl_active: 0
http.ingress_http.downstream_cx_ssl_total: 0
http.ingress_http.downstream_cx_total: 1
http.ingress_http.downstream_cx_tx_bytes_buffered: 0
http.ingress_http.downstream_cx_tx_bytes_total: 3022570
http.ingress_http.downstream_cx_websocket_active: 0
http.ingress_http.downstream_cx_websocket_total: 0
http.ingress_http.downstream_flow_control_paused_reading_total: 2318
http.ingress_http.downstream_flow_control_resumed_reading_total: 2156
http.ingress_http.downstream_rq_1xx: 0
http.ingress_http.downstream_rq_2xx: 102942
http.ingress_http.downstream_rq_3xx: 0
http.ingress_http.downstream_rq_4xx: 0
http.ingress_http.downstream_rq_5xx: 0
http.ingress_http.downstream_rq_active: 1024
http.ingress_http.downstream_rq_completed: 102942
http.ingress_http.downstream_rq_http1_total: 0
http.ingress_http.downstream_rq_http2_total: 103966
http.ingress_http.downstream_rq_idle_timeout: 0
http.ingress_http.downstream_rq_non_relative_path: 0
http.ingress_http.downstream_rq_overload_close: 0
http.ingress_http.downstream_rq_response_before_rq_complete: 96114
http.ingress_http.downstream_rq_rx_reset: 96114
http.ingress_http.downstream_rq_too_large: 0
http.ingress_http.downstream_rq_total: 103966
http.ingress_http.downstream_rq_tx_reset: 0
http.ingress_http.downstream_rq_ws_on_non_ws_route: 0
http.ingress_http.no_cluster: 0
http.ingress_http.no_route: 0
http.ingress_http.rq_direct_response: 0
http.ingress_http.rq_redirect: 0
http.ingress_http.rq_total: 103966
http.ingress_http.rs_too_large: 0
http.ingress_http.tracing.client_enabled: 0
http.ingress_http.tracing.health_check: 0
http.ingress_http.tracing.not_traceable: 0
http.ingress_http.tracing.random_sampling: 0
http.ingress_http.tracing.service_forced: 0
http2.header_overflow: 0
http2.headers_cb_no_stream: 0
http2.rx_messaging_error: 0
http2.rx_reset: 0
http2.too_many_header_frames: 0
http2.trailers: 0
http2.tx_reset: 96114
listener.0.0.0.0_53547.downstream_cx_active: 1
listener.0.0.0.0_53547.downstream_cx_destroy: 0
listener.0.0.0.0_53547.downstream_cx_total: 1
listener.0.0.0.0_53547.http.ingress_http.downstream_rq_1xx: 0
listener.0.0.0.0_53547.http.ingress_http.downstream_rq_2xx: 102942
listener.0.0.0.0_53547.http.ingress_http.downstream_rq_3xx: 0
listener.0.0.0.0_53547.http.ingress_http.downstream_rq_4xx: 0
listener.0.0.0.0_53547.http.ingress_http.downstream_rq_5xx: 0
listener.0.0.0.0_53547.http.ingress_http.downstream_rq_completed: 102942
listener.0.0.0.0_53547.no_filter_chain_match: 0
listener.admin.downstream_cx_active: 1
listener.admin.downstream_cx_destroy: 0
listener.admin.downstream_cx_total: 1
listener.admin.http.admin.downstream_rq_1xx: 0
listener.admin.http.admin.downstream_rq_2xx: 0
listener.admin.http.admin.downstream_rq_3xx: 0
listener.admin.http.admin.downstream_rq_4xx: 0
listener.admin.http.admin.downstream_rq_5xx: 0
listener.admin.http.admin.downstream_rq_completed: 0
listener.admin.no_filter_chain_match: 0
listener_manager.listener_added: 1
listener_manager.listener_create_failure: 0
listener_manager.listener_create_success: 4
listener_manager.listener_modified: 0
listener_manager.listener_removed: 0
listener_manager.total_listeners_active: 1
listener_manager.total_listeners_draining: 0
listener_manager.total_listeners_warming: 0
runtime.admin_overrides_active: 0
runtime.load_error: 0
runtime.load_success: 0
runtime.num_keys: 0
runtime.override_dir_exists: 0
runtime.override_dir_not_exists: 0
server.concurrency: 4
server.days_until_first_cert_expiring: 2147483647
server.hot_restart_epoch: 0
server.live: 1
server.memory_allocated: 21715728
server.memory_heap_size: 32505856
server.parent_connections: 0
server.total_connections: 1
server.uptime: 160
server.version: 676896
server.watchdog_mega_miss: 0
server.watchdog_miss: 0
stats.overflow: 0
cluster.service_grpc.external.upstream_rq_time: P0(1300,240) P25(2325,2084.62) P50(3450,13009.5) P75(4768.75,14163.8) P90(6910,14666.8) P95(9255,14834.5) P99(14510,14968.6) P99.5(14755,14985.4) P99.9(14951,14998.8) P100(15000,16000)
cluster.service_grpc.upstream_cx_connect_ms: P0(nan,1) P25(nan,1.025) P50(nan,1.05) P75(nan,1.075) P90(nan,1.09) P95(nan,1.095) P99(nan,1.099) P99.5(nan,1.0995) P99.9(nan,1.0999) P100(nan,1.1)
cluster.service_grpc.upstream_cx_length_ms: No recorded values
cluster.service_grpc.upstream_rq_time: P0(1300,240) P25(2325,2084.62) P50(3450,13009.5) P75(4768.75,14163.8) P90(6910,14666.8) P95(9255,14834.5) P99(14510,14968.6) P99.5(14755,14985.4) P99.9(14951,14998.8) P100(15000,16000)
http.admin.downstream_cx_length_ms: No recorded values
http.admin.downstream_rq_time: No recorded values
http.ingress_http.downstream_cx_length_ms: No recorded values
http.ingress_http.downstream_rq_time: P0(0,0) P25(0,0) P50(0,0) P75(0,0) P90(15214.2,2.06249) P95(15607.1,15150.9) P99(15921.4,16213.6) P99.5(15960.7,16606.8) P99.9(15992.1,16921.4) P100(16000,17000)
listener.0.0.0.0_53547.downstream_cx_length_ms: No recorded values
listener.admin.downstream_cx_length_ms: No recorded values
```

**Comment by lnshi** [comment]
As lizan pointed out above, after i added the [timeouts](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http_connection_management.html#timeouts) and [circuit breaker](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/circuit_breaking.html) configurations, i managed to reach the exactly same qps as my attacker reported.

Just share my envoy configuration file in case someone run into similar situation like mine:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 53547
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_grpc
                  timeout: 600s
                  max_grpc_timeout: 600s
          http_filters:
          - name: envoy.router

  clusters:
  - name: service_grpc
    connect_timeout: 30s
    type: STATIC
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: 100.64.72.26
        port_value: 53547
    circuit_breakers:
      thresholds:
        max_retries: 3
        max_requests: 100000
        max_pending_requests: 100000
``` 

Mostly `max_requests` and `max_pending_requests` do the trick in the `circuit_breakers` section.
