### ISSUE TITLE
forward_jwt doesn't seem to forward Authorization header

### ISSUE THREAD

**Issue by murphye** [istio/proxy#986]
I am experimenting with JWT auth filter and am not getting expected results with `forward_jwt: true`. I have a web service that attempts to capture the Authentication header after it passes through the filter as it may be needed for subsequent service calls. 

However, this doesn't seem to be happening as the Authorization header is missing after passing through.

Here is my spec:

```
--- 
apiVersion: config.istio.io/v1alpha2
kind: EndUserAuthenticationPolicySpec
metadata: 
  name: product-catalog-auth-policy
  namespace: product
spec: 
  jwts: 
    - issuer: https://secure-sso-rh-sso.XXX.XXX/auth/realms/master
      jwks_uri: https://secure-sso.rh-sso:8443/auth/realms/master/protocol/openid-connect/certs
      audiences: 
      - inventoryservice
      forward_jwt: true   
```

This what the Spring endpoint looks like:

```	
@GetMapping(value="/{itemId}", produces = MediaType.APPLICATION_JSON_VALUE)
	public Product getProduct(@PathVariable("itemId") long itemId, @RequestHeader("Authorization") String token
	) ...
```

This will result in a 400 bad request error as Spring is not able to match the call to an endpoint because of the missing header.
